steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Loading secrets from Secret Manager..."
        gcloud secrets versions access latest --secret=seat-env > .env
        export $(grep -v '^#' .env | xargs)

        export PROJECT_ID=$PROJECT_ID
        export SHORT_SHA=$SHORT_SHA

        echo "SPRING_DATASOURCE_URL=$$SPRING_DATASOURCE_URL"
        echo "SPRING_DATASOURCE_USERNAME=$$SPRING_DATASOURCE_USERNAME"
        echo "SPRING_DATASOURCE_PASSWORD=$$SPRING_DATASOURCE_PASSWORD"
        echo "PROJECT_ID=$$PROJECT_ID"
        echo "SHORT_SHA=$$SHORT_SHA"

        docker build \
          --build-arg SPRING_DATASOURCE_URL=$$SPRING_DATASOURCE_URL \
          --build-arg SPRING_DATASOURCE_USERNAME=$$SPRING_DATASOURCE_USERNAME \
          --build-arg SPRING_DATASOURCE_PASSWORD=$$SPRING_DATASOURCE_PASSWORD \
          -t gcr.io/$$PROJECT_ID/seat-service:$$SHORT_SHA .

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        export PROJECT_ID=$PROJECT_ID
        export SHORT_SHA=$SHORT_SHA

        gcloud container clusters get-credentials booking-cluster \
          --zone asia-southeast1-a --project $$PROJECT_ID

        kubectl apply -f k8s/seat-deployment.yaml -n booking-system

        kubectl set image deployment/seat-deployment \
          seat=gcr.io/$$PROJECT_ID/seat-service:$$SHORT_SHA \
          -n booking-system

images:
  - gcr.io/$PROJECT_ID/seat-service:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
