
apiVersion: v1
kind: Service
metadata:
  name: seat-service
  namespace: booking-system
spec:
  selector:
    app: seat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
