apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat
  template:
    metadata:
      labels:
        app: seat
    spec:
      containers:
        - name: seat
          image: gcr.io/YOUR_PROJECT_ID/seat-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: seat-env-k8s
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: seat-env-k8s
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seat-env-k8s
                  key: SPRING_DATASOURCE_PASSWORD
